package com.beng.opsyntax;

import com.beng.ErrorCode;

public enum OperatorDefinitionErrorType implements ErrorCode {
	INCOMPLETE_DEFINITION, UNEXPECTED_END, UNMATCHED_PARENTHESIS, NO_OBJECT_FOR_QUANTIFIER, QUANTIFYING_QUANTIFIER,
	MISSING_QUANTIFIER_BOUND, INVALID_QUANTIFIER_BOUND, NEGATIVE_QUANTIFIER_BOUND, LARGE_QUANTIFIER_BOUND,
	NO_OBJECT_FOR_OR, POTENTIALLY_EMPTY_OR_GROUP, EMPTY_METAQUOTE, BAD_SMALL_UNICODE_ESCAPE,
	BAD_LARGE_UNICODE_ESCAPE, BAD_HEXCODE_SCAPE, BAD_ESCAPED_CHARACTER, BAD_CHAR_RANGE, REPEATED_ARGUMENT_NAME;

	final int FIRST_VALUE = 0x10000000;

	public int getErrorCode() {
		return FIRST_VALUE + ordinal();
	}
}
